version: '3'
services:
  webapp:
    build: ./webapp
    ports:
      - 8000:8000
    volumes:
      - /tmp/static:/srv/www/static
  nginx:
    build: ./nginx
    ports:
      - 80:80
    volumes:
      - /tmp/static:/srv/www/static
    links:
      - webapp
